baseURL = "https://chriscohen.dev"
languageCode = "en-us"
title = "Chris Cohen"

[params]
  favicon="/favicon.svg"
  stylesheet="/css/global.css"
  [params.author]
    email = "chris@chriscohen.dev"
    name = "Chris Cohen"

[markup]
  [markup.highlight]
  codeFences = true
  guessSyntax = true
  hl_Lines = ''
  hl_inline = false
  lineAnchors = ''
  lineNoStart = 1
  lineNos = true
  lineNumbersInTable = true
  noClasses = true
  noHl = false
  style = 'friendly'
  tabWidth = 4

[taxonomies]
  tag = "tags"

[outputs]
  home = ['html']
  section = ['html', 'rss']
  taxonomy = ['html']
  term = ['html']
